// Lantern web app service worker (#237). Generated by vite.config.web.ts from
// src/web/sw.template.js: the build fills in the precache list and a cache
// name derived from the precached files' contents.
//
// Cache-only for the app shell. It precaches the built files, so the app opens
// offline. It never caches anything at runtime: Horizon, Soroban RPC and the
// Lantern API are other origins and pass straight through, and a same-origin
// request that isn't a precached file goes to the network untouched.
//
// Updates take effect on the next launch. A new build installs a new worker,
// which precaches the new files and then waits: it activates only once no tab
// is still running the old build. Every screen is a lazy-loaded, content-hashed
// chunk, so an open tab keeps asking for the old build's chunks; the old worker
// keeps serving them from the old cache, which is deleted only on activation.
// (Activating at once, with skipWaiting, deleted that cache under a running tab
// and its next screen failed to load.)

const CACHE = 'lantern-shell-6a3b75a5351edd04';
const PRECACHE = [
  "/",
  "/assets/Activity-D4-cTskz.js",
  "/assets/Apps-XVmtXYEa.js",
  "/assets/CashInOut-9EZN4D1r.js",
  "/assets/Earn-CAunBQe9.js",
  "/assets/Guardians-CSt4VlyD.js",
  "/assets/HoldToConfirm-onFT9NKK.js",
  "/assets/Receive-DlRzEnvI.js",
  "/assets/RecheckNotice-ulS6GoEF.js",
  "/assets/ReportAddress-CjO5ryd4.js",
  "/assets/RiskCallout-CYGvp_Ix.js",
  "/assets/Scan-BZRZdXu2.js",
  "/assets/ScanBadge-CNCDUd1K.js",
  "/assets/Send-Dg5q7zLO.js",
  "/assets/SmartAccount-DEhOa_eA.js",
  "/assets/Swap-Cf27Q_AA.js",
  "/assets/handler-D06RI_Vb.js",
  "/assets/history-Byc0MNgP.js",
  "/assets/idb-kv-BtyzxJvu.js",
  "/assets/index-BNSaKY3x.css",
  "/assets/index-BUBIqPu2.js",
  "/assets/index-CsHxT_vT.js",
  "/assets/index-CuWccChx.js",
  "/assets/index-CywX359g.js",
  "/assets/index-D_M4UD4f.js",
  "/assets/registry-BQSaiqTC.js",
  "/assets/transaction_builder-4R57jY73.js",
  "/assets/tx-DJFEhexE.js",
  "/assets/utils-BIXPYwkg.js",
  "/assets/web-Cps-FzPM.js",
  "/fonts/LICENSE-Inter.txt",
  "/fonts/LICENSE-MaterialSymbols.txt",
  "/fonts/LICENSE-RobotoMono.txt",
  "/fonts/inter-latin-ext-wght-normal.woff2",
  "/fonts/inter-latin-wght-normal.woff2",
  "/fonts/material-symbols-outlined-latin-fill-normal.woff2",
  "/fonts/roboto-mono-latin-400-normal.woff2",
  "/fonts/roboto-mono-latin-500-normal.woff2",
  "/fonts/roboto-mono-latin-ext-400-normal.woff2",
  "/fonts/roboto-mono-latin-ext-500-normal.woff2",
  "/icons/apple-touch-icon.png",
  "/icons/icon-128.png",
  "/icons/icon-16.png",
  "/icons/icon-192.png",
  "/icons/icon-32.png",
  "/icons/icon-48.png",
  "/icons/icon-512.png",
  "/index.html",
  "/logo.jpg",
  "/manifest.webmanifest",
  "/miniapps/lumen-notes/app.js",
  "/miniapps/lumen-notes/index.html",
  "/miniapps/stardust-faucet/app.js",
  "/miniapps/stardust-faucet/index.html"
];
const SHELL = '/index.html';

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith('lantern-shell-') && k !== CACHE)
            .map((k) => caches.delete(k)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Pages: the network first, so an update shows up on the next open, and the
  // precached shell when offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(async () => {
        const shell = await caches.match(SHELL, { cacheName: CACHE });
        return shell || Response.error();
      }),
    );
    return;
  }

  // Built files are content-hashed, so the precached copy is always right.
  if (!PRECACHE.includes(url.pathname)) return;
  event.respondWith(
    caches.match(url.pathname, { cacheName: CACHE }).then((hit) => hit || fetch(req)),
  );
});
