// Lantern web app service worker (#237). Generated by vite.config.web.ts from
// src/web/sw.template.js: the build fills in the precache list and a cache
// name derived from the precached files' contents.
//
// Cache-only for the app shell. It precaches the built files, so the app opens
// offline. It never caches anything at runtime: Horizon, Soroban RPC and the
// Lantern API are other origins and pass straight through, and a same-origin
// request that isn't a precached file goes to the network untouched.
//
// Updates take effect on the next launch. A new build installs a new worker,
// which precaches the new files and then waits: it activates only once no tab
// is still running the old build. Every screen is a lazy-loaded, content-hashed
// chunk, so an open tab keeps asking for the old build's chunks; the old worker
// keeps serving them from the old cache, which is deleted only on activation.
// (Activating at once, with skipWaiting, deleted that cache under a running tab
// and its next screen failed to load.)

const CACHE = 'lantern-shell-5418b99d8f06dc53';
const PRECACHE = [
  "/",
  "/assets/Activity-DMudKoe4.js",
  "/assets/Apps-D4t1K_-m.js",
  "/assets/CashInOut-BwSODtRh.js",
  "/assets/Earn-DeHlny2H.js",
  "/assets/Guardians-CqgQlHn1.js",
  "/assets/HoldToConfirm-DcQRVbMD.js",
  "/assets/Receive-Lndk2Dao.js",
  "/assets/RecheckNotice-Y8TvyLWY.js",
  "/assets/ReportAddress-55J7klN1.js",
  "/assets/RiskCallout-PWyinuW7.js",
  "/assets/Scan-fkAD1Izg.js",
  "/assets/ScanBadge-BEMR6m6r.js",
  "/assets/Send-DQP-U5os.js",
  "/assets/SmartAccount-DRTJPv0X.js",
  "/assets/Swap-BKPn3E4I.js",
  "/assets/handler-BOuFkQBZ.js",
  "/assets/history-OQOzXVtK.js",
  "/assets/idb-kv-BtyzxJvu.js",
  "/assets/index-BNSaKY3x.css",
  "/assets/index-BlLbgk1n.js",
  "/assets/index-BmaYv0oR.js",
  "/assets/index-CL1nGrGJ.js",
  "/assets/index-CuxoW6sS.js",
  "/assets/index-DYIC7z8N.js",
  "/assets/registry-DYK4Ir6_.js",
  "/assets/transaction_builder-CtJz2qSB.js",
  "/assets/tx-Clv1y15B.js",
  "/assets/utils-avs9ZGXn.js",
  "/assets/web-BiBy0nWg.js",
  "/fonts/LICENSE-Inter.txt",
  "/fonts/LICENSE-MaterialSymbols.txt",
  "/fonts/LICENSE-RobotoMono.txt",
  "/fonts/inter-latin-ext-wght-normal.woff2",
  "/fonts/inter-latin-wght-normal.woff2",
  "/fonts/material-symbols-outlined-latin-fill-normal.woff2",
  "/fonts/roboto-mono-latin-400-normal.woff2",
  "/fonts/roboto-mono-latin-500-normal.woff2",
  "/fonts/roboto-mono-latin-ext-400-normal.woff2",
  "/fonts/roboto-mono-latin-ext-500-normal.woff2",
  "/icons/apple-touch-icon.png",
  "/icons/icon-128.png",
  "/icons/icon-16.png",
  "/icons/icon-192.png",
  "/icons/icon-32.png",
  "/icons/icon-48.png",
  "/icons/icon-512.png",
  "/index.html",
  "/logo.jpg",
  "/manifest.webmanifest",
  "/miniapps/lumen-notes/app.js",
  "/miniapps/lumen-notes/index.html",
  "/miniapps/stardust-faucet/app.js",
  "/miniapps/stardust-faucet/index.html"
];
const SHELL = '/index.html';

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith('lantern-shell-') && k !== CACHE)
            .map((k) => caches.delete(k)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Pages: the network first, so an update shows up on the next open, and the
  // precached shell when offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(async () => {
        const shell = await caches.match(SHELL, { cacheName: CACHE });
        return shell || Response.error();
      }),
    );
    return;
  }

  // Built files are content-hashed, so the precached copy is always right.
  if (!PRECACHE.includes(url.pathname)) return;
  event.respondWith(
    caches.match(url.pathname, { cacheName: CACHE }).then((hit) => hit || fetch(req)),
  );
});
